name: Apply TF Dev

on:
    push:
      branches:
        - main


jobs:
  apply-dev:
    name: 'terraform apply dev'
    runs-on: ubuntu-latest
    env:
      TF_WORKING_DIR: 'project'

    defaults:
      run:
        shell: bash
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5

      - name: Terraform Init
        id: init
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            #RESOURCE_GROUP: "tfstate"
            #STORAGE_ACCOUNT: "tfstateo9e52"
            #CONTAINER_NAME: "tfstate"
        run: terraform init -backend=true -backend-config="/home/runner/work/azure_tf_templates/azure_tf_templates/project/config/dev/backend.hcl"

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform Apply
        env:
            ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
            ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
            #RESOURCE_GROUP: "tfstate"
            #STORAGE_ACCOUNT: "tfstateo9e52"
            #CONTAINER_NAME: "tfstate"
        run: terraform apply -auto-approve -var-file="/home/runner/work/azure_tf_templates/azure_tf_templates/project/config/dev/terraform.tfvars"
