on: [push]
name: Azure Synapse Workspace ARM Tempalte
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "hruthes-dataeng"
          template: ./synapse.json
          parameters: workspaceName=hruthes-synapse-armtemplate sqlAdministratorLogin=hruthes sqlAdministratorLoginPassword=Password1234! storageAccountName=hruthesdataengtestarm storageAccountKey=StorageAccountKeyARM storageAccountContainerName=armcontainer
      

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}