on: 
  push:
    paths:
      - './iac/synapse/arm_template_synapse.json'
name: Synapse ARM Template
jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: echo ${{ secrets.SYNAPSE_CREDENTIALS.login }}    

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: "hruthes-resourcegroup
          template: ./iac/synapse/arm_template_synapse.json'
          parameters: sqlAdministratorLogin=${{ secrets.SYNAPSE_CREDENTIALS.login }} 
                      sqlAdministratorLoginPassword=${{ secrets.SYNAPSE_CREDENTIALS.password }} 
                      companyTla=tou
      

        # output containerName variable from template
      - run: echo ${{ steps.deploy.outputs.containerName }}